# SPDX-FileCopyrightText: 2024-2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  spoolman2slicer:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bofh69/spoolman2slicer:latest #use :stage for the current 'main' branche or :latest for the latest stable release
    container_name: spoolman2slicer
    restart: unless-stopped
    environment:
      # Required settings
      - SM2S_SLICER_CONFIG_DIR=/configs
      - SM2S_SPOOLMAN_URL=http://spoolman.local:8000
      - SM2S_SLICER=prusaslicer

      # Optional operational settings
      - SM2S_LIVE_SYNC=true # Stay running to sync changes in real-time
      - SM2S_STARTUP_TIDY=false # Clean old files when the tool starts
      - SM2S_VERBOSE_LOGGING=false # Show detailed info for troubleshooting
      - SM2S_VARIANTS= # List of printer variants (comma-separated)
      - SM2S_CREATE_PER_SPOOL= # Options: all, least-left, most-recent
    volumes:
      - ./configs:/configs
