#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Shared fixtures for spoolman2slicer tests
"""

import json
import os
import tempfile
from pathlib import Path

import pytest
from unittest.mock import MagicMock
from spoolman2slicer.spoolman_common.api import SpoolmanClient
from spoolman2slicer.renderer import FilamentRenderer
from spoolman2slicer.engine import SyncEngine
from spoolman2slicer.constants import Slicers


@pytest.fixture
def sample_spoolman_response():
    """Sample Spoolman API response with filament data"""
    mock_path = Path(__file__).parent / "mocks" / "filaments.json"
    with open(mock_path, "r") as f:
        # Wrap the filament data in the expected list-of-dicts format
        # where each dict has a "filament" key
        filaments = json.load(f)
        return [{"id": i+1, "filament": f} for i, f in enumerate(filaments)]


@pytest.fixture
def sample_filament_data():
    """Sample single filament data"""
    mock_path = Path(__file__).parent / "mocks" / "filaments.json"
    with open(mock_path, "r") as f:
        return json.load(f)[0]


@pytest.fixture
def temp_output_dir():
    """Create a temporary directory for file outputs"""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield tmpdir


@pytest.fixture
def temp_template_dir():
    """Create a temporary directory with test templates"""
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create filename template
        filename_template = Path(tmpdir) / "filename.template"
        filename_template.write_text(
            '{% if sm2s.variant != "" %}\n'
            "{{sm2s.variant}} - {{vendor.name}} - {{name}}.{{sm2s.slicer_suffix}}\n"
            "{% else %}\n"
            "{{vendor.name}} - {{name}}.{{sm2s.slicer_suffix}}\n"
            "{% endif %}\n"
        )

        # Create filename_for_spool template
        filename_for_spool_template = Path(tmpdir) / "filename_for_spool.template"
        filename_for_spool_template.write_text(
            '{% if sm2s.variant != "" %}\n'
            "{{sm2s.variant}} - {{vendor.name}} - {{name}} - {{spool.id}}.{{sm2s.slicer_suffix}}\n"
            "{% else %}\n"
            "{{vendor.name}} - {{name}} - {{spool.id}}.{{sm2s.slicer_suffix}}\n"
            "{% endif %}\n"
        )

        # Create default.ini.template for SuperSlicer/PrusaSlicer
        default_ini = Path(tmpdir) / "default.ini.template"
        default_ini.write_text(
            "# generated by {{sm2s.name}} {{sm2s.version}}\n"
            "filament_type = {{material}}\n"
            "filament_colour = #{{color_hex}}\n"
            "filament_cost = {{price}}\n"
            "filament_density = {{density}}\n"
            "filament_diameter = {{diameter}}\n"
            'filament_settings_id = "{{id}}"\n'
            'filament_vendor = "{{vendor.name}}"\n'
            "temperature = {{settings_extruder_temp|int}}\n"
            "bed_temperature = {{settings_bed_temp|int}}\n"
        )

        # Create default.json.template for OrcaSlicer and CrealityPrint
        default_json = Path(tmpdir) / "default.json.template"
        default_json.write_text(
            json.dumps(
                {
                    "_comment": "Generated by {{sm2s.name}} {{sm2s.version}}",
                    "name": "{{name}}",
                    "filament_type": ["{{material}}"],
                    "default_filament_colour": ["#{{color_hex}}"],
                    "filament_cost": ["{{price}}"],
                    "filament_density": ["{{density}}"],
                    "filament_diameter": ["{{diameter}}"],
                    "filament_settings_id": ["{{id}}"],
                    "filament_vendor": ["{{vendor.name}}"],
                    "nozzle_temperature": ["{{settings_extruder_temp|int}}"],
                    "cool_plate_temp": ["{{settings_bed_temp|int}}"],
                },
                indent=4,
            )
        )

        # Create default.info.template for OrcaSlicer and CrealityPrint
        default_info = Path(tmpdir) / "default.info.template"
        default_info.write_text("updated_time = {{sm2s.now_int}}\n")

        # Create PLA.ini.template
        pla_ini = Path(tmpdir) / "PLA.ini.template"
        pla_ini.write_text(
            "# generated by {{sm2s.name}} {{sm2s.version}}\n"
            "filament_type = {{material}}\n"
            "filament_colour = #{{color_hex}}\n"
            "filament_cost = {{price}}\n"
            "temperature = {{settings_extruder_temp|int}}\n"
        )

        yield tmpdir


@pytest.fixture
def temp_config_files():
    """Create temporary config files for testing create_template_files"""
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create sample INI file
        ini_file = Path(tmpdir) / "test_pla.ini"
        ini_file.write_text(
            "# Filament config\n"
            "filament_type = PLA\n"
            "filament_colour = #000000\n"
            "filament_cost = 25.0\n"
            "filament_density = 1.24\n"
            "temperature = 210\n"
            "bed_temperature = 60\n"
        )

        # Create sample JSON file
        json_file = Path(tmpdir) / "test_abs.json"
        json_file.write_text(
            json.dumps(
                {
                    "name": "Test ABS",
                    "filament_type": ["ABS"],
                    "default_filament_colour": ["#FF0000"],
                    "filament_cost": ["30.0"],
                    "filament_density": ["1.04"],
                    "nozzle_temperature": ["240"],
                    "cool_plate_temp": ["100"],
                },
                indent=4,
            )
        )

        yield tmpdir


@pytest.fixture
def mock_spoolman_client():
    """Returns a mocked SpoolmanClient."""
    client = MagicMock(spec=SpoolmanClient)
    client.base_url = "http://test:7912"
    return client


@pytest.fixture
def filament_renderer(temp_template_dir, temp_output_dir):
    """Returns a FilamentRenderer pre-configured with temporary directories."""
    return FilamentRenderer(
        template_path=temp_template_dir,
        output_dir=temp_output_dir,
        slicer=Slicers.SUPERSLICER
    )


@pytest.fixture
def sync_engine(mock_spoolman_client, filament_renderer):
    """Returns a SyncEngine wired for testing."""
    return SyncEngine(
        client=mock_spoolman_client,
        renderer=filament_renderer,
        variants=[""],
        create_per_spool=None
    )
