# SPDX-FileCopyrightText: 2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Tests for the FilamentRenderer class."""

import json
import os
from pathlib import Path
import pytest
from spoolman2slicer.renderer import FilamentRenderer
from spoolman2slicer.constants import Slicers

class TestFilamentRenderer:
    """Test suite for filament profile rendering and file management."""

    def test_suffix_resolution(self, temp_template_dir, temp_output_dir):
        """Test that suffixes are correctly identified based on the slicer."""
        # SuperSlicer -> ini
        r = FilamentRenderer(temp_template_dir, temp_output_dir, Slicers.SUPERSLICER)
        assert r.suffixes == ["ini"]
        
        # OrcaSlicer -> json, info
        r = FilamentRenderer(temp_template_dir, temp_output_dir, Slicers.ORCA)
        assert r.suffixes == ["json", "info"]

    def test_get_output_filename(self, filament_renderer, sample_filament_data):
        """Test filename generation from templates."""
        data = sample_filament_data.copy()
        data["sm2s"] = {"slicer_suffix": "ini", "variant": ""}
        
        # Mock filename template produces "Vendor - Name.suffix"
        filename = filament_renderer.get_output_filename(data)
        assert filename.endswith("TestVendor - Test PLA Black.ini")

    def test_render_material_template(self, filament_renderer, sample_filament_data):
        """Test rendering with a specific material template."""
        data = sample_filament_data.copy()
        data["sm2s"] = {"name": "test", "version": "1.0", "now_int": 123}
        
        # PLA.ini.template exists in temp_template_dir
        content = filament_renderer.render_filament(data, "ini")
        assert "filament_type = PLA" in content
        assert "generated by test 1.0" in content

    def test_render_fallback_to_default(self, filament_renderer, sample_filament_data):
        """Test fallback to default.template if material template is missing."""
        data = sample_filament_data.copy()
        data["material"] = "UnknownMaterial"
        data["sm2s"] = {"name": "test", "version": "1.0", "now_int": 123}
        
        # default.ini.template exists in temp_template_dir
        content = filament_renderer.render_filament(data, "ini")
        assert "filament_type = UnknownMaterial" in content

    def test_managed_file_check(self, filament_renderer, temp_output_dir):
        """Test identification of files created by the tool."""
        managed_path = Path(temp_output_dir) / "managed.ini"
        managed_path.write_text("# generated by spoolman2slicer\ncontent")
        
        unmanaged_path = Path(temp_output_dir) / "locked.ini"
        unmanaged_path.write_text("manual config")
        
        assert filament_renderer.is_managed_file(str(managed_path)) is True
        assert filament_renderer.is_managed_file(str(unmanaged_path)) is False

    def test_delete_managed_files(self, filament_renderer, temp_output_dir):
        """Test recursive cleanup of managed files."""
        # Create a mix of files
        (Path(temp_output_dir) / "m1.ini").write_text("# generated by spoolman2slicer\n")
        (Path(temp_output_dir) / "m2.ini").write_text("# generated by spoolman2slicer\n")
        (Path(temp_output_dir) / "user.ini").write_text("important settings")
        
        deleted = filament_renderer.delete_managed_files()
        assert deleted == 2
        assert os.path.exists(os.path.join(temp_output_dir, "user.ini"))
        assert not os.path.exists(os.path.join(temp_output_dir, "m1.ini"))
    def test_render_multiple_suffixes(self, temp_template_dir, temp_output_dir, sample_filament_data):
        """Test that multiple suffixes (Orca) are rendered correctly."""
        r = FilamentRenderer(temp_template_dir, temp_output_dir, Slicers.ORCA)
        data = sample_filament_data.copy()
        data["sm2s"] = {"name": "test", "version": "1.0", "now_int": 123}
        
        # Should render both .json and .info
        for suffix in r.suffixes:
            content = r.render_filament(data, suffix)
            assert len(content) > 0 # Ensure something was rendered
            if suffix == "json":
                rendered_json = json.loads(content)
                assert rendered_json["filament_type"] == [data["material"]]
            elif suffix == "info":
                assert "updated_time =" in content

    def test_write_atomic(self, filament_renderer, temp_output_dir):
        """Test that the write method uses atomic operations."""
        target = os.path.join(temp_output_dir, "atomic_test.ini")
        content = "test content"
        
        success = filament_renderer.write(target, content)
        assert success is True
        assert os.path.exists(target)
        with open(target, "r") as f:
            assert f.read() == content
