# SPDX-FileCopyrightText: 2024-2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Filament configuration renderer and file manager."""

import os
import logging
from typing import Any, Dict, List, Optional

from jinja2 import Environment, FileSystemLoader, TemplateNotFound
from pathvalidate import sanitize_filename

from .constants import (
    DEFAULT_TEMPLATE_PREFIX,
    DEFAULT_TEMPLATE_SUFFIX,
    FILENAME_TEMPLATE,
    FILENAME_FOR_SPOOL_TEMPLATE,
    Slicers,
)
from .utils import atomic_write, is_json_slicer

logger = logging.getLogger(__name__)

class FilamentRenderer:
    """Handles Jinja2 template rendering and managed file generation."""

    def __init__(self, template_path: str, output_dir: str, slicer: Slicers):
        self.template_path = template_path
        self.output_dir = output_dir.rstrip("/").rstrip("\\")
        self.slicer = slicer
        
        self.loader = FileSystemLoader(template_path)
        self.jinja_env = Environment(loader=self.loader)
        
        # Suffixes to generate for this slicer
        self.suffixes = self._get_config_suffixes()

    def _get_config_suffixes(self) -> List[str]:
        """Determine file suffixes based on slicer type."""
        if self.slicer in (Slicers.SLIC3R, Slicers.SUPERSLICER, Slicers.PRUSA):
            return ["ini"]
        if is_json_slicer(self.slicer):
            return ["json", "info"]
        raise ValueError(f"Slicer {self.slicer} is not supported for rendering")

    def get_output_filename(self, data: Dict[str, Any], create_per_spool: bool = False) -> str:
        """
        Generate the target filename using the appropriate Jinja template.
        
        Args:
            data: The filament data dictionary (including sm2s metadata).
            create_per_spool: Whether we are in 'create-per-spool' mode.
        """
        template_name = FILENAME_FOR_SPOOL_TEMPLATE if create_per_spool else FILENAME_TEMPLATE
        try:
            template = self.jinja_env.get_template(template_name)
            raw_filename = template.render(data).strip()
            safe_filename = sanitize_filename(raw_filename, "_")
            return os.path.join(self.output_dir, safe_filename)
        except TemplateNotFound:
            logger.error(f"Filename template {template_name} not found in {self.template_path}")
            raise

    def render_filament(self, data: Dict[str, Any], suffix: str) -> str:
        """
        Render the filament configuration for a specific suffix (e.g., 'ini', 'json').
        """
        material = data.get("material", "default").lower()
        template_name = f"{material}.{suffix}.template"
        
        try:
            template = self.jinja_env.get_template(template_name)
        except TemplateNotFound:
            default_name = f"{DEFAULT_TEMPLATE_PREFIX}{suffix}{DEFAULT_TEMPLATE_SUFFIX}"
            logger.debug(f"Template {template_name} not found, falling back to {default_name}")
            try:
                template = self.jinja_env.get_template(default_name)
            except TemplateNotFound:
                logger.error(f"Default template {default_name} not found in {self.template_path}")
                raise

        return template.render(data)

    def is_managed_file(self, filepath: str) -> bool:
        """
        Check if the file was created by this tool by looking for the signature.
        """
        if not os.path.isfile(filepath):
            return False
        try:
            with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read(2048).lower()
                return "generated by spoolman2slicer" in content
        except Exception as e:
            logger.debug(f"Could not read file {filepath} for signature check: {e}")
            return False

    def write(self, filename: str, content: str) -> bool:
        """Write content to disk atomically."""
        return atomic_write(filename, content)

    def delete_managed_files(self) -> int:
        """Delete all files in the output directory managed by this tool."""
        deleted_count = 0
        if not os.path.exists(self.output_dir):
            return 0
            
        for filename in os.listdir(self.output_dir):
            for suffix in self.suffixes:
                if filename.endswith("." + suffix):
                    filepath = os.path.join(self.output_dir, filename)
                    if self.is_managed_file(filepath):
                        logger.info(f"Deleting managed file: {filepath}")
                        os.remove(filepath)
                        deleted_count += 1
        return deleted_count
